name: Build app & run tests

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
    workflow_dispatch:

jobs:
    build-and-test:
        runs-on: windows-latest

        steps:
            - name: Checkout repo and submodules
              uses: actions/checkout@v4
              with:
                  submodules: recursive

            - name: Setup Odin
              uses: laytan/setup-odin@v2.12.1
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  llvm-version: 18
                  build-type: release

            - name: Check Odin version
              run: odin version

            - name: Build app
              run: odin run ./scripts/build_app -vet-shadowing -vet-tabs -vet-cast -vet-unused-imports -vet-using-stmt -vet-semicolon -strict-style -disallow-do -warnings-as-errors -- -r

            - name: Run tests
              run: odin run ./scripts/run_tests -vet-shadowing -vet-tabs -vet-cast -vet-unused-imports -vet-using-stmt -vet-semicolon -strict-style -disallow-do -warnings-as-errors
